#!/bin/bash
# // Exporting Language to UTF-8
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'
export LC_CTYPE='en_US.utf8'

# // Export Color & Information
export RED='\033[35;1m'
export LIME='\e[92;1m'
export YELLOW='\033[1;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

# // Exporting URL Host
export Server_URL="autosc.me/aio"
export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther="XdrgVPN"

colornow=$(cat /etc/rmbl/theme/color.conf)
NC="\e[0m"
RED="\033[0;31m"
LIME="$(cat /etc/rmbl/theme/$colornow | grep -w "TEXT" | cut -d: -f2|sed 's/ //g')"
LIME="$(cat /etc/rmbl/theme/$colornow | grep -w "BG" | cut -d: -f2|sed 's/ //g')"
WH='\033[1;37m'

clear
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
author=$(cat /etc/profil)
TIMES="10"
CHATID=$(cat /etc/per/id)
KEY=$(cat /etc/per/token)
URL="https://api.telegram.org/bot$KEY/sendMessage"
domain=`cat /etc/xray/domain`
CHATID2=$(cat /etc/perlogin/id)
KEY2=$(cat /etc/perlogin/token)
URL2="https://api.telegram.org/bot$KEY2/sendMessage"
if [ ! -e /etc/xray/noobz/akun ]; then
mkdir -p /etc/xray/noobz/akun
fi
function create(){
clear

echo -e "$CYAN╭═════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}              ${LIME}• SSH PANEL MENU •               ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═════════════════════════════════════════════════╯${NC}"
read -p "Username: " user
read -p "Password: " pass
until [[ $exp =~ ^[0-9]+$ ]]; do
read -p "Exp (0 for unlimited days):" exp
done
read -p "IP LIMIT " ip

if [ ! -e /etc/sf/limit/noobs/ip/ ]; then
  mkdir -p /etc/sf/limit/noobs/ip/
fi
echo "$ip" > /etc/sf/limit/noobs/ip/$user

noobzvpns --add-user $user $pass --expired-user $user $exp
expi=`date -d "$exp days" +"%Y-%m-%d"`
useradd -e `date -d "$exp days" +"%Y-%m-%d"` -s /bin/false -M $user
exp="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$pass\n$pass\n"|passwd $user &> /dev/null
echo -e "### $user $expi $pass" >> /etc/xray/noob
clear
cat > /var/www/html/noobzvpns-$user.txt <<-END
 ◆━━━━━━━━━━━━━━━━━◆
      NOOBZVPN ACCOUNT
 ◆━━━━━━━━━━━━━━━━━◆
DOMAIN : $domain
USERNAME : $user
PASSWORD : $pass
IP LIMIT : $ip
EXP DAYS : $expi
tcp_std port :  8080
tcp_ssl port : 8443
 ◆━━━━━━━━━━━━━━━━━◆
  Example config TCP_STD 8080
 ◆━━━━━━━━━━━━━━━━━◆

EB4cHVzsbaIHhGlETDO+Ck22fVlOm01SEuUAUWIilUiZj3ho/GZ5QY+Fdur7EGcHtimx0bRpPkPYSUVldGNLCXsFP3XfuuhmgsFMFK/RNdCJO1dF1LdAFlB4FSpoxofkIxg4/ot5WJVEGKPxuK7M3hm+93/8mTKR7LO196KrYbIcDbZtui7+g0u03le97wfPfnjHgd5YVflwaagi6T1PU2z5nXp0sLPrwKY5mdvmQu2QVAiMGE/ZqdjM1m2kcYDaecChWbLz4FiMVQBjEqa5G4h7zjBmxBtXFpWvOyApTfPIKK44eBHxKoLc7FXjaEFw7ONqexhB3svRPND1XR9VtkISZLEwrXQPPv1OO2pzOaS7unutCaP7pxQoTaChCn9Z2tN5tKDn8UsB/p8ouoLZPH4g83fYzO28dV2SC064+S3PLo6MlZxmlGuBUdhPuKgrfK+Rbejas7Z8GnCglJLUyTcwuynoFQiNVqiP64hMnvB9hSNl6YDQeST20ydA8dMIG7Jg8PJ52MRO5GIxNwl9y3ut7mPrn/+ia+rgoH+kz4mww6SBEy15TeXss7ZMYZcGj7A1vtTFOfCBvvqRgBxpQ6ZPcPX2+ohuC16/fQ==

 ◆━━━━━━━━━━━━━━━━━◆
  Example config TCP_SSL 8443
 ◆━━━━━━━━━━━━━━━━━◆

EMLBHFZfH/pBoPKJNWEVgBpE6A5ZeWbnzpI4w7UFL3EEDLbefWsxq308yXcLl9+eH0CAwm6hLFDAIEZtscw6w090SyqPTK1iZxg/XVhQupV+3gkyTy/t3OeJcEGNfgOGuBGi5HVxQNiBrKIo8gQnVnR5oDVf80HbwVUHYNiayk9B8cqGRlr8bHTMs6GcevwhgWRUhOYitN20pcF91SXkQd86eIFfMVVFpM2MkRqOiL4+ZWS1GrH+r4YVC69Q50xyZAfUm+Ps17bY3hH7qcha1o2OD8RhjYqGnRzJDJEh7tfnDG6GyLgKPk+A8wxLkd+oTDKOMMsEyFA6x2NolzEYNYIsn5C2QBlEm5NAb8RJmCkFVL+L+ekiUp0NvkIRSjhVbhcl/n1CkBWkcOPYLCwyIagNJrCoD6vkoGzprqS3IAbj7RkOQqmLquAlfeEgDk6UJao/BZaoZeeIlfhDgfATDZiooLECs/h+0/2Vff1E5wnoHovDDo3FZW8xbxXXazHWdYWg8BOU3sATfhnbZd6uWsPmAg6r3jGynibibNbO1r/n88vbvB8Au319VN8KRLI4FhPc/Z9KG+njTJkmiLoG33SbPU7fF8AP

 ◆━━━━━━━━━━━━━━━━━◆
     • bumiayuvpn • 
 ◆━━━━━━━━━━━━━━━━━◆
END
if [[ -e /etc/noobz ]]; then
TEXT="
 ◆━━━━━━━━━━━━━━━━━◆
     NOOBZVPN ACCOUNT
 ◆━━━━━━━━━━━━━━━━━◆
DOMAIN : <code>$domain</code>
USERNAME : <code>$user</code>
PASSWORD : <code>$pass</code>
IP LIMIT : $ip
EXP DAYS : $expi
tcp_std port : 8080
tcp_ssl port : 8443
 ◆━━━━━━━━━━━━━━━━━◆
  Example config TCP_STD 8080
 ◆━━━━━━━━━━━━━━━━━◆

<code>EB4cHVzsbaIHhGlETDO+Ck22fVlOm01SEuUAUWIilUiZj3ho/GZ5QY+Fdur7EGcHtimx0bRpPkPYSUVldGNLCXsFP3XfuuhmgsFMFK/RNdCJO1dF1LdAFlB4FSpoxofkIxg4/ot5WJVEGKPxuK7M3hm+93/8mTKR7LO196KrYbIcDbZtui7+g0u03le97wfPfnjHgd5YVflwaagi6T1PU2z5nXp0sLPrwKY5mdvmQu2QVAiMGE/ZqdjM1m2kcYDaecChWbLz4FiMVQBjEqa5G4h7zjBmxBtXFpWvOyApTfPIKK44eBHxKoLc7FXjaEFw7ONqexhB3svRPND1XR9VtkISZLEwrXQPPv1OO2pzOaS7unutCaP7pxQoTaChCn9Z2tN5tKDn8UsB/p8ouoLZPH4g83fYzO28dV2SC064+S3PLo6MlZxmlGuBUdhPuKgrfK+Rbejas7Z8GnCglJLUyTcwuynoFQiNVqiP64hMnvB9hSNl6YDQeST20ydA8dMIG7Jg8PJ52MRO5GIxNwl9y3ut7mPrn/+ia+rgoH+kz4mww6SBEy15TeXss7ZMYZcGj7A1vtTFOfCBvvqRgBxpQ6ZPcPX2+ohuC16/fQ==</code>

 ◆━━━━━━━━━━━━━━━━━◆
  Example config TCP_SSL 8443
 ◆━━━━━━━━━━━━━━━━━◆

<code>EMLBHFZfH/pBoPKJNWEVgBpE6A5ZeWbnzpI4w7UFL3EEDLbefWsxq308yXcLl9+eH0CAwm6hLFDAIEZtscw6w090SyqPTK1iZxg/XVhQupV+3gkyTy/t3OeJcEGNfgOGuBGi5HVxQNiBrKIo8gQnVnR5oDVf80HbwVUHYNiayk9B8cqGRlr8bHTMs6GcevwhgWRUhOYitN20pcF91SXkQd86eIFfMVVFpM2MkRqOiL4+ZWS1GrH+r4YVC69Q50xyZAfUm+Ps17bY3hH7qcha1o2OD8RhjYqGnRzJDJEh7tfnDG6GyLgKPk+A8wxLkd+oTDKOMMsEyFA6x2NolzEYNYIsn5C2QBlEm5NAb8RJmCkFVL+L+ekiUp0NvkIRSjhVbhcl/n1CkBWkcOPYLCwyIagNJrCoD6vkoGzprqS3IAbj7RkOQqmLquAlfeEgDk6UJao/BZaoZeeIlfhDgfATDZiooLECs/h+0/2Vff1E5wnoHovDDo3FZW8xbxXXazHWdYWg8BOU3sATfhnbZd6uWsPmAg6r3jGynibibNbO1r/n88vbvB8Au319VN8KRLI4FhPc/Z9KG+njTJkmiLoG33SbPU7fF8AP</code>

 ◆━━━━━━━━━━━━━━━━━◆
     • 🤖@bumiayuvpn • 
 ◆━━━━━━━━━━━━━━━━━◆
"
else
TEXT="
 ◆━━━━━━━━━━━━━━━━━◆
     NOOBZVPN ACCOUNT
 ◆━━━━━━━━━━━━━━━━━◆
DOMAIN : <code>$domain</code>
USERNAME : <code>$user</code>
PASSWORD : <code>$pass</code>
IP LIMIT : $ip
EXP DAYS : $expi
tcp_std port :  8080
tcp_ssl port : 8443
 ◆━━━━━━━━━━━━━━━━━◆
  Example config TCP_STD 8080
 ◆━━━━━━━━━━━━━━━━━◆

<code>EPTaarcqHAQ4X7F0UbRe0bTdHMY/68JpxsZlQ1N/eIiMsaLhpuZFxa7TNlWTOCdnO/TavDpM2YA1O0qmIsnvAnH3Tpt2t7TzR32fjMhAUe9cIenaHtCovcyUkXSP4xMPUERfDTDGfwCPtPhPvEHL82te0EcipXdPyPwuZWhtuvoyZl0tSiKm2jpIWkFyNlS0jonu/F2rG715AKDzDcR0dd9VKiBOD+aMDn44jRLK+X2kehgl2qn5zZNuJavqRmNGzuPfuzfIwOP95l2aduxhsR4TqMplH7fjKbx6Esl2grxcOpxRNjUFce+IoFrl/mg3GzCPI6b/m/FmL+smy+ggSHthe1cG8XNnJE/aSDuTwAaeOTodX6EKawvvetbO+eJtoJ1DxBrMa1bWKJNRcsdiMBHeCue7q3rL7KCNw8Oxvy/x3cNPbszBmJaSS2ARQKEWBOC88e9MSaUNvCz8CMAlZgJljMTakLYfCI3O1/fJ86vOoZTyhnLwpy0jxRsjEnv/665Gs/U02HQDVZrloBMQyc8Lr5I8i3qIsvRtiK/xd1S8O7JpCTplLYp62jGCR4btBJyi0fDq</code>

 ◆━━━━━━━━━━━━━━━━━◆
  Example config TCP_SSL 8443
 ◆━━━━━━━━━━━━━━━━━◆

<code>EAojeSDQy9AG4Gfe5iwvfTK9Mr6G6J+50NkBJrKLm/TJJ433gIMsWitIVbYQ+tvarMY8etdHE4bKsxEy2Rlf72vnQ2lTh6CfDjzE0/Nj6bkWiAD+c7m/I+khiSWB/A+2GY95vcpZFfPyss7MdKFzGUjrV4pCQGXcx6lg7p9+HEg/NqIZ/qxC361STIHTqlHw1gqU+v5To5CghsyeP8qi1wd1kGaJJl27GIQ2CNUhZlADKb50BsAWUs14YQ1fVaxIDwVsm4Q86UfAFioxRNJPzcUG7/V7QurtkkuDrsX2h1NHe8mbJe+BhBp6/xX17dKQCuR/o0BWmuCeexafb2QRuDK1YdCFLjYFa19YH+1CjgIuBohhjn7UR72guWIOV0F/9g3crzplX1tkBdSmeeobu9w8V0XGXEs0RBIbISNuwDRoRn9GLBR60zrMEt4RFT9BXWymB4zufL3CNEwUNHPad/uKsTngLTz8bXOfpkgBJY7ARSJE6M6oPsEMJNn/8H7jVT++7ysMHR7RwXI9IIWo7GnYdWdXLlFUXbfEw7ikDyuTOZdi64I/fbe5a1GS7hf63XDUSaM=</code>

 ◆━━━━━━━━━━━━━━━━━◆
      • bumiayuvpn • 
 ◆━━━━━━━━━━━━━━━━━◆
"
fi
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
cd
if [ ! -e /etc/tele ]; then
echo -ne
else
echo "$TEXT" > /etc/notiftele
bash /etc/tele
fi
user2=$(echo "$user" | cut -c 1-3)
TIME2=$(date +'%Y-%m-%d %H:%M:%S')
TEXT2="
<code> ◆━━━━━━━━━━━━━━━━━◆</code>
<code> TRANSAKSI NOOBZVPNS SUCCES </code>
<code> ◆━━━━━━━━━━━━━━━━━◆</code>
<code>DOMAIN   :</code> <code>${domain} </code>
<code>ISP      :</code> <code>$ISP $CITY </code>
<code>DATE   :</code> <code>${TIME2} WIB </code>
<code>DETAIL   :</code> <code>Trx NOOBZVPN </code>
<code>USER :</code> <code>${user2}xxx </code>
<code>DURASI  :</code> <code>$exp Hari </code>
<code> ◆━━━━━━━━━━━━━━━━━◆</code>
<i>AutoNotif Create Akun From Server..</i>"
curl -s --max-time $TIMES -d "chat_id=$CHATID2&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL2 >/dev/null
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e   "NOOBZVPN ACCOUNT" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "DOMAIN : $( cat /etc/xray/domain )" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "USERNAME: $user" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "PASSWORD: $pass" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "IP LIMIT: $ip" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "EXP DAYS: EXP DAYS : $expi ( $exp Days )" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "tcp_std port:  8080" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "tcp_ssl port: 8443" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "Example config TCP_STD 8080" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo "" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "EJqBGr2txq01BOm/dUZZ/3C2p4b6huKslrAWVganOfZtJxfqjR6dYcbslzSRjG4A5YpPJQTlGrwmkIggiHRJb+bIYCLz/r7Eq7Q+b6K9HE0Ack4wpLkjNqCS4WHKtcb+h9dclVxgIzPuRTi93JFsH1jlRfsZ721vWs6E7TeJTGcHHIMEOBQC/1Toybsk6gueGIMz3JhhXGb12/Hr52uezrmmEE5KjaGaqd7tM0EQlh2Y4vd5C4CRjpafrufPokEo82mM0xwF8N8rcQve7ckrgioQ+E/SnZ5TXjgF5N/VQj7hluR1mTjevI/AIt03jhBUWQZFVNRvNrs75qlRHs5JSe237Tl0DIfJgJyfjwL+ep8qXcCxlptu9CcmIupvHFGa2jOWorgJhWn/nIkNT2V7JZdyc24W1Jj0xqC9YGt01QsJANKcj5iDHzUpIpJCXo9/+NKkmUwLc8YUtfLEJy8+2JbG/0xkV9Oyx4Lp2/GMKDex5cxRVv+yZ58ODqFRFlqfvsJ+QcM3HUCovJSIlJj/UBO3o7yTiArBs3nIUlTtFt4h3zCH+Xgwi+Jl91PP4imEgfKdk6jL" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo "" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "Example config TCP_SSL 8443" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo "" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "EAojeSDQy9AG4Gfe5iwvfTK9Mr6G6J+50NkBJrKLm/TJJ433gIMsWitIVbYQ+tvarMY8etdHE4bKsxEy2Rlf72vnQ2lTh6CfDjzE0/Nj6bkWiAD+c7m/I+khiSWB/A+2GY95vcpZFfPyss7MdKFzGUjrV4pCQGXcx6lg7p9+HEg/NqIZ/qxC361STIHTqlHw1gqU+v5To5CghsyeP8qi1wd1kGaJJl27GIQ2CNUhZlADKb50BsAWUs14YQ1fVaxIDwVsm4Q86UfAFioxRNJPzcUG7/V7QurtkkuDrsX2h1NHe8mbJe+BhBp6/xX17dKQCuR/o0BWmuCeexafb2QRuDK1YdCFLjYFa19YH+1CjgIuBohhjn7UR72guWIOV0F/9g3crzplX1tkBdSmeeobu9w8V0XGXEs0RBIbISNuwDRoRn9GLBR60zrMEt4RFT9BXWymB4zufL3CNEwUNHPad/uKsTngLTz8bXOfpkgBJY7ARSJE6M6oPsEMJNn/8H7jVT++7ysMHR7RwXI9IIWo7GnYdWdXLlFUXbfEw7ikDyuTOZdi64I/fbe5a1GS7hf63XDUSaM=" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo "" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e " • bumiayuvpn •" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
echo -e "◆━━━━━━━━━━━━━━━━━◆" | tee -a /etc/xray/noobz/akun/log-create-${user}.log
read -n 1 -s -r -p "Press any key to back on menu"
menu
}


function delete(){
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}             ${LIME}• DELETE NOOBZ •                   ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${NC}"

NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/xray/noob")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		echo ""
		echo "You have no existing clients!"
		exit 1
	fi

	echo ""
	echo " Select the existing client you want to remove"
	echo " Press CTRL+C to return"
	echo " ==============================="
	echo "     No  Expired   User"
	grep -E "^### " "/etc/xray/noob" | cut -d ' ' -f 2-3 | nl -s ') '
	until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
		if [[ ${CLIENT_NUMBER} == '1' ]]; then
			read -rp "Select one client [1]: " CLIENT_NUMBER
		else
			read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
		fi
	done
CLIENT_NAME=$(grep -E "^### " "/etc/xray/noob" | cut -d ' ' -f 2-3 | sed -n "${CLIENT_NUMBER}"p)
user=$(grep -E "^### " "/etc/xray/noob" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^### " "/etc/xray/noob" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
sed -i "/^### $user $exp/d" /etc/xray/noob
sed -i '/^,"'"$user"'"$/d' /etc/noobzvpns/users.json
noobzvpns --remove-user $user
expi=`date -d "$exp days" +"%Y-%m-%d"`
systemctl restart noobzvpns

clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}              ${LIME}• DELETE NOOBZ •                   ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${NC}"
echo -e ""
echo -e "$LIME USERNAME $user HAS BEEN DELETE $NC"
echo -e "$LIME EXPIRED : $expi $NC"
echo -e ""
TEXT="
<code>◆━━━━━━━━━━━━━━━━━◆</code>
<code>  DELETE NOOBZVPNS</code>
<code>◆━━━━━━━━━━━━━━━━━◆</code>
<code>DOMAIN   :</code> <code>${domain} </code>
<code>ISP      :</code> <code>$ISP $CITY </code>
<code>USERNAME :</code> <code>$user</code>
<code>EXPIRED  :</code> <code>$expi </code>
<code>◆━━━━━━━━━━━━━━━━━◆</code>
<i>Succes Delete This User...</i>
"
curl -s --max-time $TIMES -d "chat_id=$CHATIDNEW&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
cd
if [ ! -e /etc/tele ]; then
echo -ne
else
echo "$TEXT" > /etc/notiftele
bash /etc/tele
fi
echo -e "$CYAN╭══════════════════════ • ${LIME}BY${NC}${LIME} • $CYAN═══════════════════════╮${CYAN}"
echo -e "$CYAN${NC}            ${LIME}       • JS TUNNELING •          $LIME $NC"
echo -e "$CYAN╰═════════════════════════════════════════════════════╯${LIME}"
read -n 1 -s -r -p "Press any key to back on menu"
menu
}


function renew(){
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}                ${LIME}• RENEW NOOBZ •                  ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
read -p "username: " user
read -p "expired?: " exp
noobzvpns --renew-user $user --expired-user $user $exp
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}                ${LIME}• RENEW NOOBZ •                  ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
echo "USERNAME: $user"
echo "renew success!!"
echo -e "$CYAN╭══════════════════════ • ${LIME}BY${NC}${LIME} • $CYAN ═══════════════════════╮${NC}"
echo -e "$CYAN${NC}               ${LIME}      • JS TUNNELING •         $CYAN $NC"
echo -e "$CYAN╰═════════════════════════════════════════════════════╯${LIME}"
read -n 1 -s -r -p "Press any key to back on menu"
menu
}




function lock(){
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}              ${LIME}• LOCK  NOOBZ •                    ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
read -p "username: " user
noobzvpns --block-user $user
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}              ${LIME}• LOCK  NOOBZ •                    ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
echo "USERNAME: $user"
echo "locked success!!"
echo -e "$CYAN╭══════════════════════ • ${LIME}BY${NC}${LIME} • $CYAN═══════════════════════╮${NC}"
echo -e "$CYAN${NC}              ${LIME}         • JS TUNNELING •           $CYAN $NC"
echo -e "$CYAN╰═════════════════════════════════════════════════════╯${LIME}"
read -n 1 -s -r -p "Press any key to back on menu"
menu
}






function show(){

clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}               ${LIME}• MEMBER  NOOBZ •                 ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
noobzvpns --info-all-user | awk '/^\s*\+.*-> active/ {gsub(/(issued\(yyyymmdd\)|hash_key): [0-9a-f]+/, ""); print; getline; print; getline; getline; getline; print; print "═══════════════════"}'

echo -e "$CYAN╭══════════════════════ • ${LIME} BY ${NC} ${CYAN} • ═══════════════════════╮${CYAN}"
echo -e "$CYAN${NC}              ${LIME}      • bumiayuvpn •          $CYAN $LIME"
echo -e "$CYAN╰═════════════════════════════════════════════════════╯${LIME}"
read -n 1 -s -r -p "Press any key to back on menu"
menu

}



function unlock(){
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}             ${LIME}• UNLOCK  NOOBZ •                   ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
read -p "username: " user
noobzvpns --unblock-user $user
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}             ${LIME}• UNLOCK  NOOBZ •                   ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
echo "USERNAME: $user"
echo "unlocked success!!"
echo -e "$CYAN╭══════════════════════ • ${LIME}BY${NC}${LIME} • $CYAN═══════════════════════╮${NC}"
echo -e "$CYAN${NC}               ${LIME}       • bumiayuvpn •          $CYAN $NC"
echo -e "$CYAN╰═════════════════════════════════════════════════════╯${LIME}"
read -n 1 -s -r -p "Press any key to back on menu"
menu
}



function remove(){
clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}             ${LIME}• REMOVE  NOOBZ •                   ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"

read -p "Apakah Anda ingin menghapus semua user? (Y/N): " choice

if [ "$choice" == "Y" ] || [ "$choice" == "y" ]; then
    # Eksekusi perintah di sini
    echo "MENGHAPUS SEMUA USER!"
noobzvpns --remove-all-user
elif [ "$choice" == "N" ] || [ "$choice" == "n" ]; then
    echo "Membatalkan penghapusan."
menu-noobzvpns
else
    echo "Pilihan tidak valid."
fi

clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}             ${LIME}• REMOVE  NOOBZ •                   ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
echo "USERNAME: $user"
echo "unlocked success!!"
echo -e "$CYAN╭══════════════════════ • ${LIME}BY${NC}${LIME} • $CYAN═══════════════════════╮${CYAN}"
echo -e "$CYAN${NC}              ${LIME}             • bumiayuvpn •                 $CYAN $NC"
echo -e "$CYAN╰═════════════════════════════════════════════════════╯${LIME}"
read -n 1 -s -r -p "Press any key to back on menu"
menu
}




clear
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ ${NC}${LIME}             ${LIME} • NOOBZ PANEL MENU •            ${NC}$CYAN │ $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${NC}"
echo -e "$CYAN╭═══════════════════════════════════════════════════╮${NC}"
echo -e "$CYAN│ $NC  ${YELLOW}[${YELLOW}01${YELLOW}]${NC} ${LIME}• ${LIME}ADD AKUN${NC}      ${YELLOW}[${YELLOW}04${YELLOW}]${NC} ${LIME}• ${LIME}DELETE USER${NC}   $LIME $NC"
echo -e "$CYAN│ $NC  ${YELLOW}[${YELLOW}02${YELLOW}]${NC} ${LIME}• ${LIME}SHOW AKUN${NC}     ${YELLOW}[${YELLOW}05${YELLOW}]${NC} ${LIME}• ${LIME}LOCKED USER${NC}    $LIME $NC"
echo -e "$CYAN│ $NC  ${YELLOW}[${YELLOW}03${YELLOW}]${NC} ${LIME}• ${LIME}RENEW AKUN${NC}    ${YELLOW}[${YELLOW}06${YELLOW}]${NC} ${LIME}• ${LIME}UNLOCKED USER${NC}    $LIME $NC"
echo -e "$CYAN│ $NC  ${YELLOW}[${YELLOW}00${YELLOW}]${NC} ${LIME}• ${LIME}GO BACK${NC}       ${YELLOW}[${YELLOW}07${YELLOW}]${NC} ${LIME}• ${LIME}REMOVE ALL USER${NC}    $LIME $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${NC}"
echo -e "$CYAN╭═════════════════════ ${LIME} • ${LIME} BY ${LIME} • ${CYAN} ══════════════════════╮${CYAN}"
echo -e "$CYAN${NC}               ${LIME}   • bumiayuvpn •       $LIME $NC"
echo -e "$CYAN╰═══════════════════════════════════════════════════╯${LIME}"
echo -e ""
echo -ne " ${LIME}Select menu ${LIME}: ${LIME}"; read opt
case $opt in
01 | 1) clear ; create ;;
02 | 2) clear ; show ;;
03 | 3) clear ; renew ;;
04 | 4) clear ; delete ;;
05 | 5) clear ; lock ;;
06 | 6) clear ; unlock ;;
07 | 7) clear ; remove ;;
100) clear ; $up2u ;;
00 | 0) clear ; menu ;;
*) clear ; menu ;;
esac
